version: "3.8"

services:

  rstudio:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    image: my-rstudio-image:latest
    ports:
      - "127.0.0.1:8888:8888"
    environment:
      - RESTARTABLE=yes
      - GRANT_SUDO=yes
      - SHELL=/bin/zsh
    volumes:
      - ${PWD}:/home/jovyan/work
    command:
      - start-notebook.sh
      - --LabApp.default_url=/rstudio